dist: trusty
sudo: false
language: node_js
node_js: node

notifications:
  email: false
install:
- npm install
- npm install typescript -g
cache:
  directories:
  - ~/.npm
script:
- npm run lint
- npm run build

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/